# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.5

# Mod Properties
mod_version=2.0.0+26.1
maven_group=io.github.suel_ki.beautify
archives_base_name=beautify

# Dependencies
fabric_version=0.144.3+26.1
cloth_config_version=26.1.154
jade_version=26.0.5
modmenu_version=18.0.0-alpha.8